import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import Provider from "./provider";
import "./globals.css";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const nonce = (await headers()).get("x-nonce");
  // nonce is a unique value generated for each request, used to allow specific inline scripts to run while blocking others, enhancing security against XSS attacks.
  // In this code, the nonce value is retrieved from the request headers using the headers() function provided by Next.js. The nonce is then passed to the Script component as a prop, allowing the inline script to execute if it includes the correct nonce value. This helps to ensure that only trusted scripts can run on the page, providing an additional layer of security against potential cross-site scripting (XSS) attacks.
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Provider>{children}</Provider>
        <Script nonce={nonce}>console.log("CSP Working")</Script>
        {/* here nonce is passed as props  */}
      </body>
    </html>
  );
}
